development:
  secret_key_base: 409ab467550a469faefbe4c01df10342
  database:
    :username: root
    :password: change_me
    :socket: /tmp/mysql.sock
  :ao3api: &defaults
    :active: local
    :local:
      :url: localhost:3000
      :key: e1b6298a6209dd65e5df95b83b10c0f1
    :test:
      :url: test.archiveofourown.org
      :key: 717fe46d5b7a571ac65675ea63fdb573
      :username: gordon
      :password: alive
    :live:
      :url: archiveofourown.org
      :key: LIVE_API_KEY

test:
  secret_key_base: 7a543fe3d20a4889863ea9b5ea09026c
  database:
    :username: root
    :password: change_me
    :socket: /tmp/mysql.sock
  :ao3api:
    :active: local
    :local:
      :url: localhost:3000
      :key: 123


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 72a7460c7173470b88aba88f89a50287
  database:
    :username: root
    :password: change_me
    :socket: /tmp/mysql.sock
  :ao3api:
    <<: *defaults
    :active: local