development:
  secret_key_base: KEY_DEV
  database:
    :username: root
    :password: change_me
    :socket: /tmp/mysql.sock
  :ao3api: &defaults
    :active: local
    :local:
      :url: localhost:3000
      :key: KEY_AO3_LOCAL
    :test:
      :url: test.archiveofourown.org
      :key: KEY_AO3_TEST
      :username: username
      :password: password
    :live:
      :url: archiveofourown.org
      :key: LIVE_API_KEY

test:
  secret_key_base: KEY_TEST
  database:
    :username: root
    :password: change_me
    :socket: /tmp/mysql.sock
  :ao3api:
    :active: local
    :local:
      :url: localhost:3000
      :key: 123


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: KEY_PROD
  database:
    :username: root
    :password: change_me
    :socket: /tmp/mysql.sock
  :ao3api:
    <<: *defaults
    :active: local