default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  host: <%= ENV['OPEN_DOORS_TEMP_SITE_DB'] || '127.0.0.1' %>
  variables:
    sql_mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

development:
  <<: *default
  database: <%= ENV['RAILS_RELATIVE_URL_ROOT'] %>

test:
  <<: *default
  database: opendoorstempsite_test

production:
  <<: *default
  database: <%= ENV['RAILS_RELATIVE_URL_ROOT'] %>
