default: &default
  adapter: mysql2
  encoding: utf8
#  pool: 5
  username: <%= Rails.application.secrets[:database][:username] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  host: 127.0.0.1
  variables:
    sql_mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

development:
  <<: *default
  database: <%= APP_CONFIG[:sitekey] %>

test:
  <<: *default
  database: opendoorstempsite_test

production:
  <<: *default
  database: <%= APP_CONFIG[:sitekey] %>
