---
- name: Update User Password
  hosts: all
  remote_user: "{{ opendoors_user }}"
  become: yes

  tasks:
  - name: updating password
    user: name={{ opendoors_user }} update_password=always password={{ remote_pw_hash }}