---
- name: Remove Open Doors temporary site for '{{ sitekey }}'
  hosts: all
  remote_user: "{{ opendoors_user }}"
  become: yes

  vars:
    deploy_path: "{{ remote_path }}/{{ sitekey }}"
    unicorn_script: unicorn_{{ sitekey }}
    zip_file_name: "{{ sitekey }}-temp-site.zip"
    zip_file_dest: "{{ playbook_dir }}/../../"
    dropbox_dest: "/{{ ansible_date_time.year }}/{{ sitekey }}/{{ zip_file_name}}"
    dropbox_arg: "{\"path\":\"{{ dropbox_dest }}\", \"mode\": \"overwrite\"}"
    dropbox_arg_encoded: "{{ dropbox_arg }}"

  tasks:
  - name: Stop app if already running
    service:
      name: "{{ unicorn_script }}"
      state: stopped
    ignore_errors: yes

  - name: Perform database dump
    mysql_db:
      state: dump
      name: "{{ sitekey }}"
      target: "{{ deploy_path }}/{{ sitekey }}.sql"
      login_user: "{{ mysql_user }}"
      login_password: "{{ mysql_pw }}"
      login_unix_socket: "{{ mysql_socket }}"
    register: dump_database
    ignore_errors: yes

  - name: Archive app directory with database dump
    archive:
      path: "{{ deploy_path }}"
      dest: "{{ remote_path }}/{{ zip_file_name }}"

  - name: Download zip file
    fetch:
      src: "{{ remote_path }}/{{ zip_file_name }}"
      dest: "{{ zip_file_dest }}"
      flat: yes
    register: downloaded

  - name: Delete app directory
    file:
      path: "{{ deploy_path }}"
      state: absent
    when: downloaded

  - name: Delete remote copy of zip file
    file:
      path: "{{ remote_path }}/{{ sitekey }}-temp-site.zip"
      state: absent
    when: downloaded

  - name: Delete service
    file:
      path: "/etc/init.d/unicorn_{{ sitekey }}"
      state: absent

  - name: Delete MySQL database
    mysql_db:
      name: "{{ sitekey }}"
      state: absent
      login_user: "{{ mysql_user }}"
      login_password: "{{ mysql_pw }}"
      login_unix_socket: "{{ mysql_socket }}"
    when: dump_database

  - name: Restart Nginx
    service:
      name: nginx
      state: restarted
      enabled: yes

  - name: Copy archive to Dropbox
    uri:
      method: POST
      url: "https://content.dropboxapi.com/2/files/upload"
      headers:
        Authorization: "Bearer {{ dropbox_token }}"
        Dropbox-API-Arg: "{{ dropbox_arg | to_json }}"
        Content-Type: "application/octet-stream"
      src: "{{ zip_file_dest }}/{{ zip_file_name }}"
      remote_src: no
    when: downloaded